import { createRouter } from "@tanstack/react-router"
import { routeTree } from "./routeTree.gen"

// Decision: TanStack Router with file-based routing. routeTree.gen.ts is
// auto-generated by the Vite plugin on dev/build- never edit it manually.
export const router = createRouter({ routeTree })

declare module "@tanstack/react-router" {
	interface Register {
		router: typeof router
	}
}
