/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SShareTokenRouteImport } from './routes/s/$shareToken'
import { Route as DashboardSurveyIdResponsesRouteImport } from './routes/dashboard/$surveyId/responses'
import { Route as DashboardSurveyIdEditRouteImport } from './routes/dashboard/$surveyId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SShareTokenRoute = SShareTokenRouteImport.update({
  id: '/s/$shareToken',
  path: '/s/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSurveyIdResponsesRoute =
  DashboardSurveyIdResponsesRouteImport.update({
    id: '/$surveyId/responses',
    path: '/$surveyId/responses',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSurveyIdEditRoute = DashboardSurveyIdEditRouteImport.update({
  id: '/$surveyId/edit',
  path: '/$surveyId/edit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/s/$shareToken': typeof SShareTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$surveyId/edit': typeof DashboardSurveyIdEditRoute
  '/dashboard/$surveyId/responses': typeof DashboardSurveyIdResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/s/$shareToken': typeof SShareTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$surveyId/edit': typeof DashboardSurveyIdEditRoute
  '/dashboard/$surveyId/responses': typeof DashboardSurveyIdResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/s/$shareToken': typeof SShareTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$surveyId/edit': typeof DashboardSurveyIdEditRoute
  '/dashboard/$surveyId/responses': typeof DashboardSurveyIdResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/s/$shareToken'
    | '/dashboard/'
    | '/dashboard/$surveyId/edit'
    | '/dashboard/$surveyId/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/s/$shareToken'
    | '/dashboard'
    | '/dashboard/$surveyId/edit'
    | '/dashboard/$surveyId/responses'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/s/$shareToken'
    | '/dashboard/'
    | '/dashboard/$surveyId/edit'
    | '/dashboard/$surveyId/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SShareTokenRoute: typeof SShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/s/$shareToken': {
      id: '/s/$shareToken'
      path: '/s/$shareToken'
      fullPath: '/s/$shareToken'
      preLoaderRoute: typeof SShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$surveyId/responses': {
      id: '/dashboard/$surveyId/responses'
      path: '/$surveyId/responses'
      fullPath: '/dashboard/$surveyId/responses'
      preLoaderRoute: typeof DashboardSurveyIdResponsesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$surveyId/edit': {
      id: '/dashboard/$surveyId/edit'
      path: '/$surveyId/edit'
      fullPath: '/dashboard/$surveyId/edit'
      preLoaderRoute: typeof DashboardSurveyIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSurveyIdEditRoute: typeof DashboardSurveyIdEditRoute
  DashboardSurveyIdResponsesRoute: typeof DashboardSurveyIdResponsesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSurveyIdEditRoute: DashboardSurveyIdEditRoute,
  DashboardSurveyIdResponsesRoute: DashboardSurveyIdResponsesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SShareTokenRoute: SShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
